import org.gradle.api.JavaVersion

object Config {
    val minSdk = 19
    val compileSdk = 30
    val targetSdk = 30
    val javaVersion = JavaVersion.VERSION_1_8
    val buildTools = "29.0.3"
}

object Versions {
    val kotlin = "1.4.32"
    val lifecycle = "2.3.0"
    val room = "2.3.0"
    val gradle = "4.1.0"
    val retrofit = "2.9.0"
    val okhttp = "4.9.1"
    val dagger = "2.34.1"
    val coroutines = "1.4.3"
    val core_ktx = "1.3.2"
    val appcompat = "1.2.0"
    val junit = "4.13.2"
    val test_ext_junit = "1.1.2"
    val espresso = "3.3.0"
    val espresso_contrib = "3.3.0"
    val recyclerview = "1.2.0"
    val recyclerview_selection = "1.1.0"
    val cardview = "1.0.0"
    val lifecycle_extensions = "2.2.0"
    val lifecycle_ktx = "2.2.0"
    val circle_imageview = "3.1.0"
    val coil = "1.2.0"
    val swiperefreshlayout = "1.1.0"
    val nharmaan_mockito_kotlin = "3.1.0"
    val mockito_android = "3.9.3"
    val core_testing = "2.1.0"
    val kotlinx_coroutines_test = "1.4.3"
    val constraint_layout = "2.0.4"
    val support_test = "1.1.0"
    val material = "1.3.0"
    val multidex = "2.0.1"
}

object Deps {
    val androidx_recyclerview = "androidx.recyclerview:recyclerview:${Versions.recyclerview}"
    val androidx_recyclerview_selection = "androidx.recyclerview:recyclerview-selection:${Versions.recyclerview_selection}"
    val androidx_cardview = "androidx.cardview:cardview:${Versions.cardview}"
    val kotlinx_coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    val kotlinx_coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    val androidx_room_runtime = "androidx.room:room-runtime:${Versions.room}"
    val androidx_room_compiler = "androidx.room:room-compiler:${Versions.room}"
    val androidx_room = "androidx.room:room-ktx:${Versions.room}"
    val arch_lifecycle_common_java8 = "android.arch.lifecycle:common-java8:${Versions.lifecycle}"
    val arch_lifecycle_extensions = "android.arch.lifecycle:extensions:${Versions.lifecycle}"
    val androidx_lifecycle_common_java8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.lifecycle}"
    val androidx_lifecycle_extensions = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle_extensions}"
    val androidx_lifecycle_livedata_ktx = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycle_ktx}"
    val androidx_lifecycle_viewmodel_ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle_ktx}"
    val databinding_compiler = "com.android.databinding:compiler:${Versions.gradle}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val retrofit_converter_gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    val okhttp_logging_interceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    val dagger_core = "com.google.dagger:dagger:${Versions.dagger}"
    val dagger_compiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    val dagger_android = "com.google.dagger:dagger-android:${Versions.dagger}"
    val dagger_support = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    val dagger_android_processor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    val circle_imageview = "de.hdodenhof:circleimageview:${Versions.circle_imageview}"
    val coil = "io.coil-kt:coil:${Versions.coil}"
    val androidx_swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.swiperefreshlayout}"
    val nharmaan_mockito_kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Versions.nharmaan_mockito_kotlin}"
    val mockito_android = "org.mockito:mockito-android:${Versions.mockito_android}"
    val arch_core_testing = "android.arch.core:core-testing:${Versions.core_testing}"
    val kotlinx_coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.kotlinx_coroutines_test}"
    val androidx_appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    val androidx_constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.constraint_layout}"
    val junit = "junit:junit:${Versions.junit}"
    val support_test_runner = "com.android.support.test:runner:${Versions.support_test}"
    val support_test_rules = "com.android.support.test:rules:${Versions.support_test}"
    val androidx_test_ext_junit = "androidx.test.ext:junit:${Versions.test_ext_junit}"
    val androidx_espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    val espresso_contrib = "com.android.support.test.espresso:espresso-contrib:${Versions.espresso_contrib}"
    val material = "com.google.android.material:material:${Versions.material}"
    val gradle = "com.android.tools.build:gradle:${Versions.gradle}"
    val kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    val androidx_core_ktx = "androidx.core:core-ktx:${Versions.core_ktx}"
    val multidex = "com.android.support:multidex:${Versions.multidex}"

}